Add failure message
Advise the user if we were unable to decrypt the file.  This will likely
have occurred if the user was unable to unlock their encryption key.  Do
not proceed with with acting on the file (viewing/editing) and exit immediately.

diff --git a/gpg/edit b/gpg/edit
--- a/gpg/edit
+++ b/gpg/edit
@@ -53,6 +53,12 @@ if test -f "/tmp/$ENCRYPTED_FILENAME"; then
 fi
 gpg --output "/tmp/$ENCRYPTED_FILENAME" --decrypt "$1"
 
+if [ "$?" -eq 2 ]
+then
+  zenity --info --title "Error" --text "Unable to decrypt file. Password or decryption key not provided."
+  exit 3
+fi
+
 # Take a hash of the file
 CHECKSUM_BEFORE=$(sha256sum "/tmp/$ENCRYPTED_FILENAME" | cut -f 1 -d " ")
 
diff --git a/gpg/view b/gpg/view
--- a/gpg/view
+++ b/gpg/view
@@ -34,6 +34,12 @@ then
 fi
 gpg --yes --output "/tmp/$ENCRYPTED_FILENAME" --decrypt "$1"
 
+if [ "$?" -eq 2 ]
+then
+  zenity --info --title "Error" --text "Unable to decrypt file. Password or decryption key not provided."
+  exit 3
+fi
+
 # Set permissions to ensure no other system users can read the file while we're editing it
 chmod o-rwx,g-rwx "/tmp/$ENCRYPTED_FILENAME"
 
